framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'fabien@example.com'
            recipients: ['foo@example.com', 'bar@example.com']
        headers:
            From: 'Fabien <fabien@example.com>'
